# Generated by Django 3.0.1 on 2020-01-01 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('avatar', models.CharField(blank=True, max_length=300, null=True)),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('email', models.EmailField(blank=True, max_length=300, null=True)),
                ('social_media', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'ordering': ['username', 'name', 'email', 'social_media'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=300)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('date_posted', models.DateTimeField()),
                ('post_location', models.URLField(blank=True, null=True)),
                ('whitelist', models.URLField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sauceprotecc.Users')),
            ],
            options={
                'ordering': ['user', 'description', 'file_name', 'date_posted', 'whitelist'],
            },
        ),
        migrations.CreateModel(
            name='Flagged',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('url', models.URLField()),
                ('images', models.ManyToManyField(to='sauceprotecc.Image')),
            ],
        ),
    ]
