# Generated by Django 3.0.1 on 2020-01-05 01:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(default='', max_length=20, unique=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('image_address', models.URLField(default='not provided')),
                ('whitelist', models.URLField(blank=True, default='not provided', null=True)),
            ],
            options={
                'db_table': 'Image',
                'ordering': ['description', 'file_name', 'date_posted', 'whitelist'],
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('avatar', models.CharField(blank=True, max_length=300, null=True)),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('email', models.EmailField(blank=True, max_length=300, null=True)),
                ('social_media', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'ordering': ['username', 'name', 'email', 'social_media'],
            },
        ),
        migrations.CreateModel(
            name='Flagged',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('url', models.URLField()),
                ('images', models.ManyToManyField(to='sauceprotecc.Image')),
            ],
        ),
    ]
