# Generated by Django 3.0.1 on 2020-01-02 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sauceprotecc', '0002_auto_20200102_0138'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='image',
            table='Image',
        ),
    ]
